services:
  spring_boot_app:
    build:
      dockerfile: Dockerfile
    environment:
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - POSTGRES_URL=${POSTGRES_URL:-jdbc:postgresql://postgres:5432/postgres}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-default_internal_postgres_password}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-default_internal_postgres_password}
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
